### PR TITLE
2.0rc

### PR DESCRIPTION
**Pull request by thebergamo**
In this version, the entire structure is changed.

### CODE REVIEW

**Comment by thebergamo** [comment]
@rafaeljesus @AdrieanKhisbe @tdantas can review this PR? I'll merge this manually, because have much files changed to auto merge.

**Comment by AdrieanKhisbe** [comment]
fast overview, nothing made my eyes bleed, or react. 
But i'm a bit out of context I am.

So consider this an `ACK` :)

**Comment by rafaeljesus** [comment]
I don't have branch permissions so I'll let my considerations right here,
- I'd add on Readme standard logo [js-standard-style](https://github.com/feross/standard)
- Would be very elegant to use ansible instead of shell script 
- I definitely would use coroutines with promises like below.
- It would be pretty handy to have postgresql(maybe another project) as a database configured with knex, bookshelf, sequelize, etc..

``` javascript
exports.start = co.wrap(function *() {
  try {
    yield registerDatabase()
    yield registerCorePlugins()
    yield registerModules()
    yield startServer()
  } catch (err) {
    catchError(err)
  }
})
```

Note: bluebird coroutines does not return a promise
- Also on tests with inject-then module

``` javascript
beforeEach(function *() {
  yield db.Todo.removeAsync()
  let response = yield server.injectThen({
    method: 'GET',
    url: '/todo',
    headers: {'Authorization': `Bearer ${token}`}
  }) 
  expect(response).to.have.property('result');
  expect(response.result).to.have.length.least(0);
});
```
- I'd refactor from that 

``` javascript
let registerRoutes = routes.map((route) => {
  return {
    register: require(route)
  };
});
```

to this

``` javascript
  let registerRoutes = routes.map((route) => ({register: require(route)}))
```

@thebergamo done with code review

**Comment by thebergamo** [comment]
@rafaeljesus thanks for your review! 

Ansible is cool, but shell is more easy to deal for new users and is less one dependency.

About PostgreSQL is cool, and I think release new branches using other databases. After finishing the v2.0 I will add support for other databases in new branches.

I will adding the generators in this version.. 

About Standard, will put in Readme, but I use semistandard :)

**Comment by rafaeljesus** [comment]
@thebergamo I totally disagree with semistandard hahaha :100: 

Hey maybe we could make it modular creating a db npm module and a api module,

Npm is free for Open Sources repos isn't it?

What you think?

**Comment by thebergamo** [comment]
creating a npm module huh? I'm not entire sure about this propose. 

Can tell me more about this idea?

**Comment by Talento90** [comment]
Waiting for this PR :+1:

**Comment by thebergamo** [comment]
Probably this PR needs a new refactor :(

**Comment by Talento90** [comment]
Why do you say that? If you need help I am able to help you :+1:

**Comment by thebergamo** [comment]
Very thanks @Talento90, maybe is better accept this PR and build the new refactorings in another PR.
The refactorings is in most part update the syntax for new es6, now available in Node 4+

**Pull request closed without merging**
